// Import the bcryptjs library for secure password hashing
const bcrypt = require('bcryptjs');
// Import the database connection pool to execute SQL queries
const pool = require('../database/db');

/**
 * Service to fetch all users from the database.
 * Includes join logic to retrieve descriptive company and role names.
 */
const getAllUsers = async () => {
    // Define the SQL query to select user details and join with companies and roles tables
    const sql = `
        SELECT u.id, u.username, u.email, u.status, u.last_login,
               c.company_name, r.role_name
        FROM users u
        JOIN companies c ON u.company_id = c.id
        JOIN roles r ON u.role_id = r.id
    `;
    // Execute the query using the connection pool and wait for the results
    const [rows] = await pool.query(sql);
    // Return the array of user records to the caller
    return rows;
};

/**
 * Service to handle the creation of a new user by an administrator.
 */
const adminCreateUser = async (userData) => {
    // Destructure the user data fields from the provided userData object
    const { username, email, password, company_id, role_id, status } = userData;

    // Generate a secure salt for hashing the password (10 rounds is the industry standard)
    const salt = await bcrypt.genSalt(10);
    // Create a secure hash of the plain-text password using the generated salt
    const password_hash = await bcrypt.hash(password, salt);

    // Prepare the SQL statement to insert the new user record into the database
    const sql = 'INSERT INTO users (username, email, password_hash, company_id, role_id, status) VALUES (?, ?, ?, ?, ?, ?)';
    // Execute the insert query with the hashed password and provided user details
    const [result] = await pool.query(sql, [username, email, password_hash, company_id, role_id, status || 'PENDING']);

    // Return the unique ID generated by the database for the new user record
    return result.insertId;
};

// Export the user service functions so they can be utilized by controllers
module.exports = {
    // Export the function to get all users
    getAllUsers,
    // Export the function for admin-controlled user creation
    adminCreateUser
};
